### PR TITLE
Add support for Laravel 6

### PR DESCRIPTION
**Pull request by fweinrich**
Please support Laravel v6.

### CODE REVIEW

**Comment by mohammad-fouladgar** [comment]
@fweinrich  Can you fix the `.travis.yml` file for complete the CI build?

**Comment by fweinrich** [comment]
I excluded php7.1 should be alright now

**Comment by mohammad-fouladgar** [comment]
Thanks. But we need set the php:{version},LARAVEL and TESTBENCH='{version}' in `.travis.yml` file.

Please take a look at the file.Also, visit the this repo: https://github.com/orchestral/testbench#version-compatibility

We should increase the major version after this PR.

**Comment by mohammad-fouladgar** [comment]
v1.1.2 Support For Laravel 6

**Pull request closed without merging**
